from enum import Enum


class PrayerCalculationJuristicMethod(Enum):
    JAFARI_ITHNA_ASHARI = 0
    KARACHI_UNIVERSITY_OF_ISLAMIC_SCIENCES = 1
    ISNA_ISLAMIC_SOCIETY_OF_NORTH_AMERICA = 2
    MWL_MUSLIM_WORLD_LEAGUE = 3
    MECCA_UMM_AL_QURA = 4
    EGYPTIAN_GENERAL_AUTHORITY_OF_SURVEY = 5
    CUSTOM_SETTING = 6
    UNIVERSITY_OF_TEHRAN_INSTITUTE_OF_GEOPHYSICS = 7
    ALGERIAN_MINISTER_OF_RELIGOUS_AFFAIRS_AND_WAKFS = 8
    GULF_90_MINUTES_FIXED_ISHA = 9
    EGYPTIAN_GENERAL_AUTHORITY_OF_SURVEY_BIS = 10
    UOIF_UNION_DES_ORGANISATIONS_ISLAMIQUES_DE_FRANCE = 11
    SISTEM_INFORMASI_HISAB_RUKYAT_INDONESIA = 12
    DIYANET_ISLERI_BASKANLIGI = 13
    GERMANY_CUSTOM = 14
    RUSSIAN_CUSTOM = 15


class AsrJuristicMethod(Enum):
    STANDARD_SHAFI_HANBALI_MALIKI = 0
    HANAFI = 1


class HighLatitudes(Enum):
    NONE = 0
    MIDNIGHT = 1
    ONE_SEVENTH = 2
    ANGLE = 3


class TimeFormat(Enum):
    FORMAT_24_HR = 0
    FORMAT_12_HR = 1
    FORMAT_12_HR_NO_SUFFIX = 2
    FLOATING_NUMBER = 3


class MaghribRule(Enum):
    ANGLE = 0
    FIXED_MINUTES = 1


class IshaRule(Enum):
    ANGLE = 0
    FIXED_MINUTES = 1
